### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by zeeev** [isovic/minialign#2]
I'm not sure what the memory requirements are for minialign.  I've allowed for 60GB per job (20G/thread) as many of my target sequences are large.  The jobs are dying when they hit our memory cap.  When logged into the node, i see the memory constituently climb.  This makes me think there is a memory leak somewhere.  I don't have a good test dataset to valgrind with.

**Comment by isovic** [comment]
Could be actually. Come to think of it, I think I fixed a leak in Racon a while ago, but this code is older. Let me inspect.

**Comment by isovic** [comment]
Debugging on the phone ftw.!
There were three legacy leaks actually.
Nicely spotted!
Try it now.

**Comment by zeeev** [comment]
"Seems" stable, there still might be a slow leak... or just variation in the size of the query.

**Comment by zeeev** [comment]
There is still a leak.

**Comment by isovic** [comment]
Hmm...I Valgrinded on a Lambda and no leaks showed up (with --leak-check=full), and I tested on a larger E. Coli PacBio dataset (albeit without Valgrind but just monitored the memory consumption) and it seemed stable.

Though, you may have not pulled the last version?
https://github.com/isovic/minialign/blob/master/src/mhap.cc#L107

**Comment by zeeev** [comment]
Yup, you're right.
